### ISSUE TITLE
Error: Couldn't find preset "stage-0" relative to directory

### ISSUE THREAD

**Issue by idoco** [conveyal/react-select-geocoder#1]
Having some trouble making this work.
What am I doing wrong? Do you happen to recognize this error? 

```
C:\workspace\GeoJsonHack\web_client>npm install
npm WARN install Couldn't install optional dependency: Unsupported
npm WARN EPEERINVALID babel-loader@6.2.1 requires a peer of webpack@^1.0.0 but none was installed.
npm WARN EPACKAGEJSON react_test@1.0.0 No description
npm WARN EPACKAGEJSON react_test@1.0.0 No repository field.

C:\workspace\GeoJsonHack\web_client>webpack
Hash: 34432255a5fbe863e03c
Version: webpack 2.0.6-beta
Time: 5745ms
       Asset    Size  Chunks             Chunk Names
../bundle.js  190 kB       0  [emitted]  main
    + 206 hidden modules

ERROR in ./~/react-select-geocoder/build/index.js
Module build failed: Error: Couldn't find preset "stage-0" relative to directory "C:\\workspace\\GeoJsonHack\\web_client\\node_modules\\react-select-geocoder"
    at OptionManager.mergePresets (C:\workspace\GeoJsonHack\web_client\node_modules\babel-core\lib\transformation\file\options\option-manager.js:327:17)
    at OptionManager.mergeOptions (C:\workspace\GeoJsonHack\web_client\node_modules\babel-core\lib\transformation\file\options\option-manager.js:287:12)
    at OptionManager.addConfig (C:\workspace\GeoJsonHack\web_client\node_modules\babel-core\lib\transformation\file\options\option-manager.js:221:10)
    at OptionManager.findConfigs (C:\workspace\GeoJsonHack\web_client\node_modules\babel-core\lib\transformation\file\options\option-manager.js:370:30)
    at OptionManager.init (C:\workspace\GeoJsonHack\web_client\node_modules\babel-core\lib\transformation\file\options\option-manager.js:412:12)
    at File.initOptions (C:\workspace\GeoJsonHack\web_client\node_modules\babel-core\lib\transformation\file\index.js:191:75)
    at new File (C:\workspace\GeoJsonHack\web_client\node_modules\babel-core\lib\transformation\file\index.js:122:22)
    at Pipeline.transform (C:\workspace\GeoJsonHack\web_client\node_modules\babel-core\lib\transformation\pipeline.js:42:16)
    at transpile (C:\workspace\GeoJsonHack\web_client\node_modules\babel-loader\index.js:14:22)
    at Object.module.exports (C:\workspace\GeoJsonHack\web_client\node_modules\babel-loader\index.js:88:12)
 @ ./NewEntryForm.js 2:15-47
```

Thanks.

**Comment by idoco** [comment]
I'm not sure what the problem was, I played with npm and re-installed and now it works
